import type { Verse } from "@/types/domain";

/**
 * Kids verse set — curated from verses/Kids.pdf.
 * Simpler language, shorter passages, five kid-friendly themes.
 */

export const KIDS_VERSES: Verse[] = [
  /* ------------------------------------------------------------------ */
  /*  ABOUT GOD (theme: "kids-god")                                     */
  /* ------------------------------------------------------------------ */
  {
    id: "kids-john316",
    reference: "John 3:16",
    translation: "NIV",
    parts: ["For God so ", " the world that he gave his one and only ", ", that whoever believes in him shall not perish but have ", " life."],
    answers: ["LOVED", "SON", "ETERNAL"],
    decoys: ["MADE", "GIFT", "GOOD"],
    themeId: "kids-god",
    themeLabel: "About God",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
    isDailyFeatured: true,
    kjv: {
      parts: ["For God so ", " the world, that he gave his only begotten ", ", that whosoever believeth in him should not perish, but have ", " life."],
      answers: ["LOVED", "SON", "EVERLASTING"],
      decoys: ["MADE", "GIFT", "GOOD"],
    },
  },
  {
    id: "kids-ps4610",
    reference: "Psalm 46:10",
    translation: "NIV",
    parts: ["He says, \"Be ", ", and know that I am ", ".\""],
    answers: ["STILL", "GOD"],
    decoys: ["QUIET", "LORD", "GOOD"],
    themeId: "kids-god",
    themeLabel: "About God",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
    kjv: {
      parts: ["Be ", ", and know that I am ", "."],
      answers: ["STILL", "GOD"],
      decoys: ["QUIET", "LORD", "GOOD"],
    },
  },
  {
    id: "kids-isa435",
    reference: "Isaiah 43:5",
    translation: "NIV",
    parts: ["Do not be ", " for I am ", " you."],
    answers: ["AFRAID", "WITH"],
    decoys: ["SCARED", "NEAR", "FOR"],
    themeId: "kids-god",
    themeLabel: "About God",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
    kjv: {
      parts: ["Fear ", ", for I am ", " thee."],
      answers: ["NOT", "WITH"],
      decoys: ["NONE", "NEAR", "FOR"],
    },
  },
  {
    id: "kids-matt2820",
    reference: "Matthew 28:20",
    translation: "NIV",
    parts: ["And surely I am with you ", ", to the very end of the ", "."],
    answers: ["ALWAYS", "AGE"],
    decoys: ["FOREVER", "WORLD", "DAY"],
    themeId: "kids-god",
    themeLabel: "About God",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
    kjv: {
      parts: ["And, lo, I am with you ", ", even unto the end of the ", "."],
      answers: ["ALWAY", "WORLD"],
      decoys: ["FOREVER", "AGE", "DAY"],
    },
  },
  {
    id: "kids-ps1459",
    reference: "Psalm 145:9",
    translation: "NIV",
    parts: ["The LORD is ", " to all; he has ", " over all he has made."],
    answers: ["GOOD", "COMPASSION"],
    decoys: ["KIND", "MERCY", "LOVE"],
    themeId: "kids-god",
    themeLabel: "About God",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-gen11",
    reference: "Genesis 1:1",
    translation: "NIV",
    parts: ["In the ", ", God ", " the heavens and the earth."],
    answers: ["BEGINNING", "CREATED"],
    decoys: ["START", "MADE", "FORMED"],
    themeId: "kids-god",
    themeLabel: "About God",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
    kjv: {
      parts: ["In the ", ", God ", " the heaven and the earth."],
      answers: ["BEGINNING", "CREATED"],
      decoys: ["START", "MADE", "FORMED"],
    },
  },
  {
    id: "kids-prov305",
    reference: "Proverbs 30:5",
    translation: "NIV",
    parts: ["Every word of God is ", "; he is a ", " to those who take refuge in him."],
    answers: ["FLAWLESS", "SHIELD"],
    decoys: ["TRUE", "LIGHT", "HELPER"],
    themeId: "kids-god",
    themeLabel: "About God",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-rom1013",
    reference: "Romans 10:13",
    translation: "NIV",
    parts: ["For everyone who ", " on the name of the Lord will be ", "."],
    answers: ["CALLS", "SAVED"],
    decoys: ["PRAYS", "BLESSED", "LOVED"],
    themeId: "kids-god",
    themeLabel: "About God",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-jas117",
    reference: "James 1:17",
    translation: "NIV",
    parts: ["Every good and ", " gift is from ", "."],
    answers: ["PERFECT", "ABOVE"],
    decoys: ["GREAT", "GOD", "HEAVEN"],
    themeId: "kids-god",
    themeLabel: "About God",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },

  /* ------------------------------------------------------------------ */
  /*  ABOUT JESUS (theme: "kids-jesus")                                 */
  /* ------------------------------------------------------------------ */
  {
    id: "kids-john146",
    reference: "John 14:6",
    translation: "NIV",
    parts: ["Jesus answered, \"I am the ", " and the ", " and the life. No one comes to the Father except through ", ".\""],
    answers: ["WAY", "TRUTH", "ME"],
    decoys: ["LIGHT", "DOOR", "GOD"],
    themeId: "kids-jesus",
    themeLabel: "About Jesus",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
    isDailyFeatured: true,
    kjv: {
      parts: ["Jesus saith unto him, I am the ", ", the ", ", and the life: no man cometh unto the Father, but by ", "."],
      answers: ["WAY", "TRUTH", "ME"],
      decoys: ["LIGHT", "DOOR", "GOD"],
    },
  },
  {
    id: "kids-heb138",
    reference: "Hebrews 13:8",
    translation: "NIV",
    parts: ["Jesus Christ is the same ", ", today and ", "."],
    answers: ["YESTERDAY", "FOREVER"],
    decoys: ["ALWAYS", "TOMORROW", "EVER"],
    themeId: "kids-jesus",
    themeLabel: "About Jesus",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-matt1926",
    reference: "Matthew 19:26",
    translation: "NIV",
    parts: ["With man this is ", ", but with ", " all things are possible."],
    answers: ["IMPOSSIBLE", "GOD"],
    decoys: ["HARD", "JESUS", "FAITH"],
    themeId: "kids-jesus",
    themeLabel: "About Jesus",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-john141",
    reference: "John 14:1",
    translation: "NIV",
    parts: ["Do not let your hearts be ", ". You believe in God; believe also in ", "."],
    answers: ["TROUBLED", "ME"],
    decoys: ["AFRAID", "JESUS", "HIM"],
    themeId: "kids-jesus",
    themeLabel: "About Jesus",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-john1633",
    reference: "John 16:33",
    translation: "NIV",
    parts: ["I have told you these things, so that in me you may have ", ". In this world you will have ", ". But take heart! I have overcome the ", "."],
    answers: ["PEACE", "TROUBLE", "WORLD"],
    decoys: ["JOY", "PAIN", "SIN"],
    themeId: "kids-jesus",
    themeLabel: "About Jesus",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "intermediate",
    kjv: {
      parts: ["These things I have spoken unto you, that in me ye might have ", ". In the world ye shall have ", ": but be of good cheer; I have overcome the ", "."],
      answers: ["PEACE", "TRIBULATION", "WORLD"],
      decoys: ["JOY", "TROUBLE", "SIN"],
    },
  },
  {
    id: "kids-rom58",
    reference: "Romans 5:8",
    translation: "NIV",
    parts: ["But God ", " his own love for us in this: While we were still ", ", Christ died for us."],
    answers: ["DEMONSTRATES", "SINNERS"],
    decoys: ["SHOWS", "LOST", "PEOPLE"],
    themeId: "kids-jesus",
    themeLabel: "About Jesus",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-gal522",
    reference: "Galatians 5:22-23",
    translation: "NIV",
    parts: ["But the fruit of the Spirit is ", ", joy, peace, forbearance, ", ", goodness, faithfulness, gentleness and ", "."],
    answers: ["LOVE", "KINDNESS", "SELF-CONTROL"],
    decoys: ["HOPE", "MERCY", "PATIENCE"],
    themeId: "kids-jesus",
    themeLabel: "About Jesus",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "intermediate",
  },

  /* ------------------------------------------------------------------ */
  /*  ABOUT FAITH (theme: "kids-faith")                                 */
  /* ------------------------------------------------------------------ */
  {
    id: "kids-jer2911",
    reference: "Jeremiah 29:11",
    translation: "NIV",
    parts: ["For I know the ", " I have for you, declares the LORD, plans to ", " you and not to harm you, plans to give you hope and a ", "."],
    answers: ["PLANS", "PROSPER", "FUTURE"],
    decoys: ["THOUGHTS", "BLESS", "LIFE"],
    themeId: "kids-faith",
    themeLabel: "About Faith",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "intermediate",
    isDailyFeatured: true,
  },
  {
    id: "kids-prov35",
    reference: "Proverbs 3:5",
    translation: "NIV",
    parts: ["Trust in the ", " with all your heart and do not lean on your own ", "."],
    answers: ["LORD", "UNDERSTANDING"],
    decoys: ["GOD", "WISDOM", "KNOWLEDGE"],
    themeId: "kids-faith",
    themeLabel: "About Faith",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-heb116",
    reference: "Hebrews 11:6",
    translation: "NIV",
    parts: ["And without ", " it is impossible to please God, because anyone who comes to him must ", " that he exists and that he rewards those who earnestly ", " him."],
    answers: ["FAITH", "BELIEVE", "SEEK"],
    decoys: ["HOPE", "TRUST", "FIND"],
    themeId: "kids-faith",
    themeLabel: "About Faith",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "intermediate",
  },
  {
    id: "kids-rom1017",
    reference: "Romans 10:17",
    translation: "NIV",
    parts: ["Consequently, faith comes from ", ", and hearing through the ", " about Christ."],
    answers: ["HEARING", "WORD"],
    decoys: ["READING", "MESSAGE", "TRUTH"],
    themeId: "kids-faith",
    themeLabel: "About Faith",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-2cor418",
    reference: "2 Corinthians 4:18",
    translation: "NIV",
    parts: ["So we fix our eyes not on what is ", ", but on what is unseen, since what is seen is ", ", but what is unseen is eternal."],
    answers: ["SEEN", "TEMPORARY"],
    decoys: ["VISIBLE", "PASSING", "SHORT"],
    themeId: "kids-faith",
    themeLabel: "About Faith",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "intermediate",
  },
  {
    id: "kids-ps11824",
    reference: "Psalm 118:24",
    translation: "NIV",
    parts: ["The LORD has done it this very day; let us ", " today and be ", "."],
    answers: ["REJOICE", "GLAD"],
    decoys: ["SING", "HAPPY", "PRAISE"],
    themeId: "kids-faith",
    themeLabel: "About Faith",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },

  /* ------------------------------------------------------------------ */
  /*  ABOUT CHARACTER (theme: "kids-character")                         */
  /* ------------------------------------------------------------------ */
  {
    id: "kids-phil413",
    reference: "Philippians 4:13",
    translation: "NIV",
    parts: ["I can do all this through him who gives me ", "."],
    answers: ["STRENGTH"],
    decoys: ["POWER", "HOPE", "FAITH"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
    isDailyFeatured: true,
    kjv: {
      parts: ["I can do all things through ", " which strengtheneth me."],
      answers: ["CHRIST"],
      decoys: ["GOD", "JESUS", "HIM"],
    },
  },
  {
    id: "kids-josh19",
    reference: "Joshua 1:9",
    translation: "NIV",
    parts: ["Be strong and ", ". Do not be ", "; do not be discouraged, for the LORD your God will be with you wherever you ", "."],
    answers: ["COURAGEOUS", "AFRAID", "GO"],
    decoys: ["BRAVE", "SCARED", "WALK"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "intermediate",
  },
  {
    id: "kids-1pet57",
    reference: "1 Peter 5:7",
    translation: "NIV",
    parts: ["Cast all your ", " on him because he ", " for you."],
    answers: ["ANXIETY", "CARES"],
    decoys: ["WORRIES", "LOVES", "WATCHES"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-eph432",
    reference: "Ephesians 4:32",
    translation: "NIV",
    parts: ["Be kind and ", " to one another, forgiving each other, just as in Christ God ", " you."],
    answers: ["COMPASSIONATE", "FORGAVE"],
    decoys: ["GENTLE", "LOVED", "BLESSED"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-1cor1031",
    reference: "1 Corinthians 10:31",
    translation: "NIV",
    parts: ["So whether you eat or ", ", or whatever you do, do it all for the ", " of God."],
    answers: ["DRINK", "GLORY"],
    decoys: ["SLEEP", "HONOR", "LOVE"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-ps13914",
    reference: "Psalm 139:14",
    translation: "NIV",
    parts: ["I praise you because I am fearfully and ", " made; your works are ", ", I know that full well."],
    answers: ["WONDERFULLY", "WONDERFUL"],
    decoys: ["BEAUTIFULLY", "AMAZING", "GREAT"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-phil44",
    reference: "Philippians 4:4",
    translation: "NIV",
    parts: ["Rejoice in the Lord ", ". I will say it again: ", "!"],
    answers: ["ALWAYS", "REJOICE"],
    decoys: ["FOREVER", "PRAISE", "SING"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-matt544",
    reference: "Matthew 5:44",
    translation: "NIV",
    parts: ["But I tell you, love your ", " and pray for those who ", " you."],
    answers: ["ENEMIES", "PERSECUTE"],
    decoys: ["FRIENDS", "HURT", "HATE"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-luke631",
    reference: "Luke 6:31",
    translation: "NIV",
    parts: ["Do to ", " as you would have them do to ", "."],
    answers: ["OTHERS", "YOU"],
    decoys: ["THEM", "US", "ALL"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-col320",
    reference: "Colossians 3:20",
    translation: "NIV",
    parts: ["Children, obey your ", " in everything, for this ", " the Lord."],
    answers: ["PARENTS", "PLEASES"],
    decoys: ["FAMILY", "HONORS", "SERVES"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-ps563",
    reference: "Psalm 56:3",
    translation: "NIV",
    parts: ["When I am ", ", I put my trust in ", "."],
    answers: ["AFRAID", "YOU"],
    decoys: ["SCARED", "GOD", "HIM"],
    themeId: "kids-character",
    themeLabel: "About Character",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },

  /* ------------------------------------------------------------------ */
  /*  ABOUT LOVE (theme: "kids-love")                                   */
  /* ------------------------------------------------------------------ */
  {
    id: "kids-1john419",
    reference: "1 John 4:19",
    translation: "NIV",
    parts: ["We love because he ", " loved ", "."],
    answers: ["FIRST", "US"],
    decoys: ["ALWAYS", "ALL", "THEM"],
    themeId: "kids-love",
    themeLabel: "About Love",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
    isDailyFeatured: true,
  },
  {
    id: "kids-1john418",
    reference: "1 John 4:18",
    translation: "NIV",
    parts: ["There is no ", " in love. But perfect love drives out ", "."],
    answers: ["FEAR", "FEAR"],
    decoys: ["HATE", "DOUBT", "SIN"],
    themeId: "kids-love",
    themeLabel: "About Love",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-1john48",
    reference: "1 John 4:8",
    translation: "NIV",
    parts: ["Whoever does not love does not know God, because God is ", "."],
    answers: ["LOVE"],
    decoys: ["GOOD", "LIGHT", "GREAT"],
    themeId: "kids-love",
    themeLabel: "About Love",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-ps1361",
    reference: "Psalm 136:1",
    translation: "NIV",
    parts: ["Give thanks to the LORD, for he is ", ". His love endures ", "."],
    answers: ["GOOD", "FOREVER"],
    decoys: ["GREAT", "ALWAYS", "EVER"],
    themeId: "kids-love",
    themeLabel: "About Love",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
  {
    id: "kids-rom129",
    reference: "Romans 12:9",
    translation: "NIV",
    parts: ["Love must be ", ". Hate what is evil; cling to what is ", "."],
    answers: ["SINCERE", "GOOD"],
    decoys: ["TRUE", "RIGHT", "PURE"],
    themeId: "kids-love",
    themeLabel: "About Love",
    devotional: "",
    applicationPrompt: "What does this verse mean to you?",
    difficulty: "beginner",
  },
];

/** Kids theme options for the topic picker */
export const KIDS_THEME_OPTIONS = [
  {
    id: "kids-god",
    label: "About God",
    description: "Learn who God is and how much He loves you.",
    prompt: "What does this verse mean to you?",
  },
  {
    id: "kids-jesus",
    label: "About Jesus",
    description: "What Jesus said and did — and what it means for you.",
    prompt: "What does this verse mean to you?",
  },
  {
    id: "kids-faith",
    label: "About Faith",
    description: "Verses to help you trust God even when it's hard.",
    prompt: "What does this verse mean to you?",
  },
  {
    id: "kids-character",
    label: "About Character",
    description: "How God wants us to treat others and live each day.",
    prompt: "What does this verse mean to you?",
  },
  {
    id: "kids-love",
    label: "About Love",
    description: "God's love for us, and how we can love others.",
    prompt: "What does this verse mean to you?",
  },
];
