import { Verse } from "@/types/domain";

export const LOCAL_VERSES: Verse[] = [
  {
    id: "rom323",
    reference: "Romans 3:23",
    translation: "NIV",
    parts: ["For all have ", " and fall ", " of the glory of God."],
    answers: ["SINNED", "SHORT"],
    decoys: ["FAILED", "AWAY", "FAR"],
    themeId: "core",
  },
  {
    id: "jn119",
    reference: "1 John 1:9",
    translation: "NIV",
    parts: [
      "If we ",
      " our sins, he is ",
      " and just and will ",
      " us our sins and ",
      " us from all unrighteousness.",
    ],
    answers: ["CONFESS", "FAITHFUL", "FORGIVE", "PURIFY"],
    decoys: ["HIDE", "CLEANSE", "FREE", "HOLY"],
    themeId: "core",
  },
  {
    id: "rom623",
    reference: "Romans 6:23",
    translation: "NIV",
    parts: [
      "For the wages of ",
      " is death, but the ",
      " of God is eternal ",
      " in Christ Jesus our Lord.",
    ],
    answers: ["SIN", "GIFT", "LIFE"],
    decoys: ["DEATH", "PEACE", "EVIL", "GRACE"],
    themeId: "core",
  },
  {
    id: "jn316",
    reference: "John 3:16",
    translation: "NIV",
    parts: [
      "For God so ",
      " the world that he ",
      " his one and only ",
      ", that whoever ",
      " in him shall not perish but have eternal life.",
    ],
    answers: ["LOVED", "GAVE", "SON", "BELIEVES"],
    decoys: ["SENT", "CHILD", "TRUSTS", "SAVED"],
    themeId: "core",
  },
  {
    id: "php413",
    reference: "Philippians 4:13",
    translation: "NIV",
    parts: ["I can do all this through ", " who ", " me strength."],
    answers: ["CHRIST", "GIVES"],
    decoys: ["JESUS", "GOD", "LORD"],
    themeId: "core",
  },
  {
    id: "rom828",
    reference: "Romans 8:28",
    translation: "NIV",
    parts: [
      "And we know that in all things ",
      " works for the ",
      " of those who ",
      " him, who have been called according to his purpose.",
    ],
    answers: ["GOD", "GOOD", "LOVE"],
    decoys: ["JESUS", "GRACE", "BEST", "SEEK"],
    themeId: "core",
  },
  {
    id: "pro35",
    reference: "Proverbs 3:5-6",
    translation: "NIV",
    parts: [
      " ",
      " in the Lord with all your ",
      " and lean not on your own ",
      ". In all your ways ",
      " to him, and he will make your paths ",
      ".",
    ],
    answers: ["TRUST", "HEART", "UNDERSTANDING", "SUBMIT", "STRAIGHT"],
    decoys: ["BELIEVE", "SOUL", "WISDOM", "CLEAR"],
    themeId: "core",
  },
  {
    id: "jer2911",
    reference: "Jeremiah 29:11",
    translation: "NIV",
    parts: [
      "For I know the ",
      " I have for you, declares the Lord, plans to ",
      " you and not to harm you, plans to give you ",
      " and a future.",
    ],
    answers: ["PLANS", "PROSPER", "HOPE"],
    decoys: ["THOUGHTS", "BLESS", "PEACE"],
    themeId: "core",
  },
  {
    id: "matt1128",
    reference: "Matthew 11:28",
    translation: "NIV",
    parts: [
      "Come to me, all you who are ",
      " and ",
      ", and I will give you rest.",
    ],
    answers: ["WEARY", "BURDENED"],
    decoys: ["TIRED", "HEAVY", "BROKEN"],
    themeId: "core",
  },
  {
    id: "ps4610",
    reference: "Psalm 46:10",
    translation: "NIV",
    parts: [
      "Be ",
      " and know that I am God. I will be ",
      " among the nations, I will be exalted in the earth.",
    ],
    answers: ["STILL", "EXALTED"],
    decoys: ["QUIET", "CALM", "PRAISED"],
    themeId: "core",
  },
];
